# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
global:
  registry: ''
  tag: 2026.2.0-rc1
  vssStackTag: ''
  pullPolicy: ''
  vectordbBackend: vdms
  proxy:
    httpProxy: ''
    httpsProxy: ''
    noProxy: localhost,127.0.0.1,.svc.cluster.local
  env:
    embeddingModelName: ''
    vsIndexName: video_frame_embeddings
    aggregationInitialK: '1000'
    vdbMetricType: IP
    vdbIndexType: FLAT

image:
  repository: ''
  pullPolicy: IfNotPresent

replicaCount: 1
service:
  type: ClusterIP
  port: 8000

retriever:
  logLevel: INFO
  maxTopK: '1000'
  searchEngine: FaissFlat
  distanceStrategy: IP
  milvusTextField: text
  milvusMetadataField: ''

embeddingService:
  waitForHealthy: true
  healthUrl: "http://multimodal-embedding-serving:8000/health"
  healthTimeoutSeconds: 5
  retryIntervalSeconds: 5

podSecurityContext: {}
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
resources: {}
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 15
