# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: live-video-alert-agent-chart
description: A Helm chart for deploying the Live Video Alert Agent with OpenVINO VLM inference
type: application
version: 2026.2.0-rc1-helm
appVersion: "2.0.0"

dependencies:
  - name: ovms
    version: 1.0.1
    repository: "file://subchart/ovms"
  - name: ovms-llm
    version: 1.0.1
    repository: "file://subchart/ovms-llm"
    condition: ovms-llm.enabled
  - name: app
    version: 1.0.1
    repository: "file://subchart/app"
  - name: mqtt
    version: 1.0.0
    repository: "file://subchart/mqtt"
  - name: alert-agent-service
    version: 1.0.0
    repository: "file://subchart/alert-agent-service"
  - name: metrics-manager
    version: "2026.2.0-helm"
    repository: "file://subchart/metrics-manager"
