services:
  tfcc:
    build:
      context: ..
      dockerfile: docker/Dockerfile_TFCC.dockerfile
      network: host
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - BASE=${BASE}
        - BASE_VERSION=${BASE_VERSION}
    image: tfcc:latest
    network_mode: host
    environment:
      - no_proxy=localhost,127.0.0.1
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - ZE_ENABLE_ALT_DRIVERS=libze_intel_vpu.so 
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/dri:/dev/dri"
    group_add:
      - ${VIDEO_GROUP_ID}
      - ${RENDER_GROUP_ID}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.Xauthority:/home/openvino/.Xauthority:rw"
    working_dir: /home/openvino/metro-2.0
    entrypoint: /bin/bash
    tty: true
    stdin_open: true

  tfcc-npu:
    build:
      context: ..
      dockerfile: docker/Dockerfile_TFCC.dockerfile
      network: host
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - BASE=${BASE}
        - BASE_VERSION=${BASE_VERSION}
    image: tfcc:latest
    network_mode: host
    environment:
      - no_proxy=localhost,127.0.0.1
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - ZE_ENABLE_ALT_DRIVERS=libze_intel_vpu.so 
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/dri:/dev/dri"
      - "/dev/accel:/dev/accel"
    group_add:
      - ${VIDEO_GROUP_ID}
      - ${RENDER_GROUP_ID}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "${HOME}/.Xauthority:/home/openvino/.Xauthority:rw"
    working_dir: /home/openvino/metro-2.0
    entrypoint: /bin/bash
    tty: true
    stdin_open: true
