{{/*
Copyright (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if .Values.global.usePvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vdms-vectordb.fullname" . }}-pvc
  {{- if .Values.global.keepPvc }}
  annotations:
    helm.sh/resource-policy: keep   # Prevent Helm from deleting PVC on uninstall
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.claimSize | default "10Gi" }}
{{- end }}
