# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  office-poc-ui:
    image: ${REGISTRY:-opea}/office-poc-ui:${TAG:-latest}
    build:
      context: ../..
      dockerfile: ./ui/docker/Dockerfile.ui
