#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: mraas-postgres
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "mraas-postgres-port"
      port: 5432
  selector:
    app: mraas-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mraas-postgres
  name: deployment-mraas-postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mraas-postgres
  template:
    metadata:
      labels:
        app: mraas-postgres
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: mraas-postgres
        env:
          - name: AppName
            value: ModelRegistry
          - name: POSTGRES_DB
            value: "{{ .Values.env.POSTGRES_DB }}"
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.env.POSTGRES_PASSWORD }}"
          - name: POSTGRES_USER
            value: "{{ .Values.env.POSTGRES_USER }}"
        image: postgres:13
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        volumeMounts:
          - name: postgres-temp-data
            mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
        - name: postgres-temp-data
          emptyDir: {}