# Copyright (c) 2025 Intel Corporation.
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: {{ $.Values.config.prometheus.int.prometheus_port }}
      targetPort: {{ $.Values.config.prometheus.int.prometheus_port }}
      nodePort: {{ $.Values.config.prometheus.ext.prometheus_port }}
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: deployment-prometheus
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: {{ $.Values.config.prometheus.int.prometheus_port }}
          env:
            - name: HTTP_PROXY
              value: {{ $.Values.env.http_proxy }}
            - name: HTTPS_PROXY
              value: {{ $.Values.env.https_proxy }}
            - name: NO_PROXY
              value: otel-collector,localhost,127.0.0.1,{{ $.Values.env.HOST_IP }}
          volumeMounts:
            - name: prometheus-config-input
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
      volumes:
        - name: prometheus-config-input
          configMap:
            name: prometheus-config
