# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: coturn
description: Coturn TURN server for WebRTC NAT traversal.
type: application
version: 2026.2.0-rc1-helm
appVersion: "4.6.2"
