apiVersion: v2
name: smart-nvr
description: A Helm chart for Smart NVR 
version: 2026.2.0-rc1
dependencies:
  - name: frigate
    version: 1.2.3
    repository: "file://subchart/frigate"
  - name: nvr-event-router
    version: 1.2.3
    repository: "file://subchart/nvr-event-router"
  - name: nvr-event-router-ui
    version: 1.2.3
    repository: "file://subchart/nvr-event-router-ui"
  - name: mqtt-broker
    version: 1.2.3
    repository: "file://subchart/mqtt-broker"
  - name: redis
    version: 1.2.3
    repository: "file://subchart/redis"