"""
Report field catalog — the domain data contract for classroom reports.

Declares which placeholders a classroom report can contain, grouped and
bilingually labeled for the online editor's "Available Data" reference panel.
This is business knowledge (what a report is made of), deliberately kept apart
from the generic docx mechanics in ``template_manager``.

Each field carries a ``kind`` recording *how it is filled*:
  - "raw":       a value/metric that comes directly from data or metadata and
                 must never be invented by the LLM (numbers, names, timestamps).
  - "generated": free-text that genuinely requires LLM summarization/assessment.

``kind`` drives the split-fill pipeline (see ``report_generator`` +
``raw_field_mapper``): "raw" fields are filled directly from measured data,
only "generated" fields are sent to the LLM. Several "raw" fields have no
structured data source wired up yet and fall back to a neutral no-data marker.
"""

# Allowed values for a field's ``kind``.
FIELD_KINDS = frozenset({"raw", "generated"})

REPORT_TEMPLATE_FIELD_GROUPS = [
    {"group_key": "basic_info", "fields": [
        # Basic info is not derivable from audio/video, so the teacher types it in
        # (input="manual"). A blank manual field is treated as deselected (dropped).
        {"code": "school_name", "kind": "raw", "input": "manual", "label_key": "school_name"},
        {"code": "class_name", "kind": "raw", "input": "manual", "label_key": "class_name"},
        {"code": "course_name", "kind": "raw", "input": "manual", "label_key": "course_name"},
        {"code": "teacher_name", "kind": "raw", "input": "manual", "label_key": "teacher_name"},
        # Auto metadata: always present, not a user-toggleable checkbox.
        {"code": "report_time", "kind": "raw", "always_on": True, "label_key": "report_time"},
        {"code": "report_delay_after_class", "kind": "raw", "always_on": True, "label_key": "report_delay_after_class"},
        # Pre-formatted keyword-count note (e.g. "（共8个）"), empty when none. See resolve_raw_fields.
        {"code": "keywords_count_note", "kind": "raw", "always_on": True, "label_key": "keywords_count"},
        # Number of camera feeds recorded, counted from the VA output markers.
        # Always-on: filled directly and shown via a template placeholder, never a
        # user-toggleable checkbox.
        {"code": "video_source_count", "kind": "raw", "always_on": True, "label_key": "video_source_count"},
    ]},
    {"group_key": "class_overview", "fields": [
        {"code": "duration", "kind": "raw", "label_key": "duration"},
        {"code": "attendance", "kind": "raw", "label_key": "attendance"},
    ]},
    {"group_key": "teaching_behavior", "fields": [
        {"code": "question_count", "kind": "raw", "label_key": "question_count"},
        {"code": "teaching_duration", "kind": "raw", "label_key": "teaching_duration"},
        {"code": "speaking_speed", "kind": "raw", "label_key": "speaking_speed"},
        {"code": "pacing_assessment", "kind": "raw", "label_key": "pacing_assessment"},
    ]},
    {"group_key": "engagement", "fields": [
        {"code": "hand_raise_count", "kind": "raw", "label_key": "hand_raise_count"},
        {"code": "hand_raise_avg", "kind": "raw", "label_key": "hand_raise_avg"},
    ]},
    {"group_key": "knowledge_structure", "fields": [
        # Keywords and key_difficulty are extracted directly from the summary's
        # ## Keywords / ## Key Difficulty Points sections (produced by the
        # summarizer's
        # single full-transcript pass), so they are "raw" — filled from data, not
        # re-generated by the report LLM. See DataCollector._read_class_summary.
        {"code": "keywords", "kind": "raw", "label_key": "keywords"},
        {"code": "mindmap", "kind": "raw", "label_key": "mindmap"},
        {"code": "key_difficulty", "kind": "raw", "label_key": "key_difficulty"},
        # Deterministic per-point mention counts (teacher transcript + OCR text),
        # pre-assembled into one summary string, never an LLM guess.
        {"code": "difficulty_mentions_summary", "kind": "raw", "label_key": "difficulty_mentions_summary"},
    ]},
    {"group_key": "teaching_effectiveness", "fields": [
        {"code": "interaction_level", "kind": "generated", "label_key": "interaction_level"},
        {"code": "classroom_atmosphere", "kind": "generated", "label_key": "classroom_atmosphere"},
        {"code": "recommendations", "kind": "generated", "label_key": "recommendations"},
    ]},
]


def get_known_field_codes() -> set:
    """Flat set of every placeholder code the pipeline can fill."""
    return {f["code"] for g in REPORT_TEMPLATE_FIELD_GROUPS for f in g["fields"]}


def get_field_kinds() -> dict:
    """Map every known field code to its ``kind`` ("raw" | "generated").

    Drives the split-fill pipeline: "raw" codes are filled directly from measured
    data, "generated" codes go to the LLM. Codes absent from this map (custom
    template placeholders) are treated as generated.
    """
    return {f["code"]: f["kind"] for g in REPORT_TEMPLATE_FIELD_GROUPS for f in g["fields"]}


def get_always_on_codes() -> set:
    """Codes always included (auto metadata, e.g. report_time) — not user-toggleable."""
    return {f["code"] for g in REPORT_TEMPLATE_FIELD_GROUPS for f in g["fields"]
            if f.get("always_on")}


def get_manual_field_codes() -> set:
    """Codes the teacher types in manually (not derivable from audio/video)."""
    return {f["code"] for g in REPORT_TEMPLATE_FIELD_GROUPS for f in g["fields"]
            if f.get("input") == "manual"}


def _validate_catalog() -> None:
    """Fail fast at import time on a malformed catalog (typo'd kind, dup code)."""
    seen = set()
    for group in REPORT_TEMPLATE_FIELD_GROUPS:
        for field in group["fields"]:
            code = field["code"]
            if code in seen:
                raise ValueError(f"Duplicate field code in catalog: {code!r}")
            seen.add(code)
            if field["kind"] not in FIELD_KINDS:
                raise ValueError(f"Field {code!r} has invalid kind {field['kind']!r}")


_validate_catalog()
