# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: dlstreamer-pipeline-server
description: Intel DL Streamer Pipeline Server — GStreamer-based video analytics with VLM inference.
type: application
version: 2026.2.0-rc1-helm
appVersion: "2026.0.0-ubuntu24"
