# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: mediamtx
description: MediaMTX — WHIP/WebRTC signaling relay and media server.
type: application
version: 2026.2.0-rc1-helm
appVersion: "1.11.3"
