# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[General]
TcpServerPort=0

[UdpEndpoint px4]
Mode=Server
Address=0.0.0.0
Port=14550

[UdpEndpoint broadcast]
Mode=Normal
Address=255.255.255.255
Port=14541
