apiVersion: v2
name: vdmsvectordb
description: A Helm chart for deploying VDMS VectorDB components in the Live Video Captioning for embedding storage and retrieval.
type: application
version: 0.1.0
appVersion: "2.0"
