apiVersion: v2
name: vdmsvectordb
description: A Helm chart for deploying VDMS VectorDB components in the Live Video Captioning for embedding storage and retrieval.
type: application
version: 2026.2.0-rc1-helm
appVersion: "2.0"
