global:
  persistence:
    rwxEnabled: false

frigate:
  mode: default
rtspTest:
  enabled: false
frigate-vms:
  service:
    frigate:
      nodePort: null

nginx:
  service:
    app:
      nodePort: null

minio-service:
  service:
    minioApi:
      nodePort: null
    minioConsole:
      nodePort: null

nvr-event-router:
  service:
    nvrEventRouter:
      nodePort: null
