apiVersion: v2
name: multimodal-embedding
description: A Helm chart for deploying Multimodal Embedding components in the Live Video Captioning for embedding generation and management.
type: application
version: 2026.2.0-rc1-helm
appVersion: "2.0"
