apiVersion: v2
name: multimodal-embedding
description: A Helm chart for deploying Multimodal Embedding components in the Live Video Captioning for embedding generation and management.
type: application
version: 0.1.0
appVersion: "2.0"
