name: Feature Request
description: File a feature request. 
title: '[FEATURE]: <Software> - <Summary>'
labels: ['FEATURE','TRIAGE']
body:

  - type: markdown
    attributes:
      value: <br>To expedite issue processing please search open and closed issues before submitting a new one. Existing issues often contain information about workarounds, resolution, or progress updates.

  - type: textarea
    attributes:
      label: Feature Description
      description: A clear and concise description of the problem or missing capability. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution Description
      description: If you have a solution in mind, please describe it.

  - type: textarea
    attributes:
      label: Alternative Description
      description: Have you considered any alternative solutions or workarounds?
      
