# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[General]
TcpServerPort=0

[UdpEndpoint px4]
Mode=Server
Address=0.0.0.0
Port=14540

[UdpEndpoint companion]
Mode=Server
Address=0.0.0.0
Port=14541
