# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'apm-metrics-manager'
    static_configs:
      - targets: ['apm-metrics:9273']

  - job_name: 'apm-metrics-manager-api'
    static_configs:
      - targets: ['apm-metrics:9090']
    metrics_path: /metrics

  - job_name: 'apm-agent'
    static_configs:
      - targets: ['apm-agent:5002']
    metrics_path: /metrics

  - job_name: 'apm-storage'
    static_configs:
      - targets: ['apm-storage:5001']
    metrics_path: /metrics
