apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-service
  labels:
    {{- include "lvs.minio.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: minio-service
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/minio-service-configmap.yaml") . | sha256sum }}
      labels:
        app: minio-service
        {{- include "lvs.minio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: minio
          image: {{ .Values.images.minio }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - server
            - /data
            - --address
            - :80
            - --console-address
            - :81
          envFrom:
            - configMapRef:
                name: minio-service-config
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "lvs.minio.fullname" . }}-credentials
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "lvs.minio.fullname" . }}-credentials
                  key: MINIO_ROOT_PASSWORD
          ports:
            - containerPort: 80
              name: api
            - containerPort: 81
              name: console
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: {{ include "lvs.minio.fullname" . }}-minio-data
