# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: smart-traffic-intersection-agent
description: A Helm chart for deploying the Smart Traffic Intersection Agent application
type: application
version: 2026.2.0-rc1-helm
appVersion: "1.0.0"

dependencies:
  - name: ovms
    version: "2026.2.0-rc1-helm"
    repository: "file://subcharts/ovms"
    condition: ovms.enabled

  - name: metrics-manager
    version: "2026.2.0-rc1-helm"
    repository: "file://subcharts/metrics-manager"
    condition: metricsManager.enabled
    alias: metricsManager
