# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: smart-route-planning-agent
description: A chart for deploying Smart Route Planning Agent Application
type: application
version: 2026.2.0-rc1-helm
appVersion: "1.0.0"
