mqtt:
  enabled: true
  host: mqtt-broker
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

logger:
  default: info

detect:
  enabled: false

snapshots:
  enabled: false

record:
  enabled: true
  retain:
    days: 1
    mode: all
