#!/usr/bin/env python3
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# These contents may have been developed with support from one or more
# Intel-operated generative artificial intelligence solutions.
"""
Shared synthetic KPI fixtures for use across test files.

  LEVEL1_KPI  — minimal valid Level 1 kpi.json payload
  LEVEL2_KPI  — minimal valid Level 2 kpi_level2.json payload derived from LEVEL1_KPI

Pipeline: /camera/raw → Sensor → Perception → Planning → /cmd_vel
"""

LEVEL1_KPI = {
    'schema_version': 'level1_v1',
    'throughput_hz': 20.0,
    'mean_latency_ms': 50.0,
    'min_latency_ms': 45.0,
    'max_latency_ms': 82.0,
    'max_jitter_ms': 5.0,
    'min_jitter_ms': 0.5,
    'mean_jitter_ms': 2.0,
    'jitter_stdev_ms': 1.0,
    'cpu_mean_pct': 30.0,
    'cpu_max_pct': 60.0,
    'per_node': {
        '/camera_node': {
            'throughput_hz': 20.0,
            'mean_latency_ms': 10.0,
            'min_latency_ms': 7.0,
            'max_latency_ms': 16.0,
            'mean_jitter_ms': 1.0,
            'max_jitter_ms': 3.0,
            'num_samples': 200,
            'primary_input': '/camera/raw',
            'primary_output': '/camera/image',
            'pipeline_stage': 'Sensor',
        },
        '/detector_node': {
            'throughput_hz': 18.0,
            'mean_latency_ms': 40.0,
            'min_latency_ms': 30.0,
            'max_latency_ms': 58.0,
            'mean_jitter_ms': 3.0,
            'max_jitter_ms': 8.0,
            'num_samples': 180,
            'primary_input': '/camera/image',
            'primary_output': '/detections',
            'pipeline_stage': 'Perception',
        },
        '/planner_node': {
            'throughput_hz': 15.0,
            'mean_latency_ms': 60.0,
            'min_latency_ms': 45.0,
            'max_latency_ms': 82.0,
            'mean_jitter_ms': 4.0,
            'max_jitter_ms': 12.0,
            'num_samples': 150,
            'primary_input': '/detections',
            'primary_output': '/cmd_vel',
            'pipeline_stage': 'Planning',
        },
    },
    'pairs': [
        {
            'node': '/camera_node',
            'input': '/camera/raw',
            'output': '/camera/image',
            'pipeline_stage': 'Sensor',
            'n': 200,
            'mean_ms': 10.0,
            'stdev_ms': 1.2,
            'min_ms': 7.0,
            'p50_ms': 10.0,
            'p90_ms': 12.0,
            'p99_ms': 14.0,
            'max_ms': 16.0,
            'trigger_count': 200,
            'fps': 20.0,
            'jitter_mean_ms': 1.0,
            'jitter_max_ms': 3.0,
        },
        {
            'node': '/detector_node',
            'input': '/camera/image',
            'output': '/detections',
            'pipeline_stage': 'Perception',
            'n': 180,
            'mean_ms': 40.0,
            'stdev_ms': 3.5,
            'min_ms': 30.0,
            'p50_ms': 39.0,
            'p90_ms': 46.0,
            'p99_ms': 52.0,
            'max_ms': 58.0,
            'trigger_count': 180,
            'fps': 18.0,
            'jitter_mean_ms': 3.0,
            'jitter_max_ms': 8.0,
        },
        {
            'node': '/planner_node',
            'input': '/detections',
            'output': '/cmd_vel',
            'pipeline_stage': 'Planning',
            'n': 150,
            'mean_ms': 60.0,
            'stdev_ms': 5.0,
            'min_ms': 45.0,
            'p50_ms': 59.0,
            'p90_ms': 68.0,
            'p99_ms': 75.0,
            'max_ms': 82.0,
            'trigger_count': 150,
            'fps': 15.0,
            'jitter_mean_ms': 4.0,
            'jitter_max_ms': 12.0,
        },
    ],
    'metadata': {
        'name': 'test_session',
        'datetime': '2026-04-28T00:00:00Z',
        'hostname': 'testhost',
        'arch': 'x86_64',
        'os': 'Linux 6.8.0',
        'data_path': '/tmp/test_session',
        'framework_version': '0.1.8',
        'ros_distro': 'jazzy',
        'hardware': {
            'cpu_model': 'Test CPU',
            'cpu_cores': 8,
            'gpu_model': None,
            'total_ram_gb': 16.0,
        },
    },
}

# Derived from LEVEL1_KPI: e2e mean = sum of stage means (10 + 40 + 60 = 110 ms)
LEVEL2_KPI = {
    'schema_version': 'level2_v1',
    'pipeline': {
        'input_topic': '/camera/raw',
        'output_topic': '/cmd_vel',
        'stage_sequence': ['Sensor', 'Perception', 'Planning'],
    },
    'e2e_latency_ms': {
        'mean': 110.0,
        'p50': 108.0,
        'p90': 126.0,
        'p99': 141.0,
        'max': 156.0,
        'n': 150,
        'method': 'chained',
    },
    'throughput_hz': 15.0,
    'drop_rate_pct': 25.0,
    'bottleneck_stage': 'Planning',
    'stage_latency_ms': {
        'Sensor': {
            'mean_ms': 10.0,
            'p50_ms': 10.0,
            'p90_ms': 12.0,
            'p99_ms': 14.0,
            'max_ms': 16.0,
            'n': 200,
            'representative_node': '/camera_node',
            'representative_input': '/camera/raw',
            'representative_output': '/camera/image',
        },
        'Perception': {
            'mean_ms': 40.0,
            'p50_ms': 39.0,
            'p90_ms': 46.0,
            'p99_ms': 52.0,
            'max_ms': 58.0,
            'n': 180,
            'representative_node': '/detector_node',
            'representative_input': '/camera/image',
            'representative_output': '/detections',
        },
        'Planning': {
            'mean_ms': 60.0,
            'p50_ms': 59.0,
            'p90_ms': 68.0,
            'p99_ms': 75.0,
            'max_ms': 82.0,
            'n': 150,
            'representative_node': '/planner_node',
            'representative_input': '/detections',
            'representative_output': '/cmd_vel',
        },
    },
    'cpu_mean_pct': 30.0,
    'cpu_max_pct': 60.0,
    'level1_source': '/tmp/test_session/kpi.json',
    'metadata': {
        'name': 'test_session',
        'datetime': '2026-04-28T00:00:00Z',
        'hostname': 'testhost',
        'arch': 'x86_64',
        'os': 'Linux 6.8.0',
        'data_path': '/tmp/test_session',
        'framework_version': '0.1.8',
        'ros_distro': 'jazzy',
        'hardware': {
            'cpu_model': 'Test CPU',
            'cpu_cores': 8,
            'gpu_model': None,
            'total_ram_gb': 16.0,
        },
    },
}
