# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v2
name: milvus-standalone
description: Standalone Milvus backend for Live Video Search
type: application
version: 2026.2.0-helm
appVersion: "2.6.14"
