apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lvs.nginx.fullname" . }}-nginx
  labels:
    {{- include "lvs.nginx.labels" . | nindent 4 }}
data:
  nginx.conf.template: |
{{ tpl .Values.nginx.config . | nindent 4 }}
