# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel
---
specSchema: "DeploymentPackage"
schemaVersion: "0.1"
$schema: "https://schema.intel.com/catalog.orchestrator/0.1/schema"

name: "sp"
displayName: "sp"
description: "Smart Parking Sample Application"
version: "1.1.0"

applications:
  - name: sp-app
    version: 1.1.0

defaultNamespaces:
  sp-app: sp

deploymentProfiles:
  - name: "default"
    description: "Uses CPU for inferencing"
    applicationProfiles:
      - application: "sp-app"
        profile: "default"
  - name: "with-intel-gpu"
    description: "Uses Intel GPU for inferencing, needs Intel GPU extension"
    applicationProfiles:
      - application: "sp-app"
        profile: "with-intel-gpu"
