#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

FROM python:3.13.4-slim

COPY mqtt-publisher/requirements.txt /
RUN pip3 install --no-cache-dir -r requirements.txt
COPY mqtt-publisher/publisher.py /
COPY simulation_data/windturbine_data.csv /

ARG TIMESERIES_UID
ARG TIMESERIES_USER_NAME
RUN groupadd $TIMESERIES_USER_NAME -g $TIMESERIES_UID && \
    useradd -r -u $TIMESERIES_UID -g $TIMESERIES_USER_NAME $TIMESERIES_USER_NAME

    RUN apt-get remove --purge -y --allow-remove-essential perl-base

USER ${TIMESERIES_USER_NAME}

HEALTHCHECK --interval=5m CMD exit 0

ENTRYPOINT ["python3", "-u", "publisher.py"]
