# Copyright Intel Corporation

namespace:
DOCKER_USERNAME: ''
DOCKER_PASSWORD: ''
imagePullPolicy: Always
storageClassName: manual
mqtt_broker:
  image: eclipse-mosquitto
  imageTag: 2.0.22
coturn:
  image: coturn/coturn
  imageTag: 4.12.0
mediamtx:
  image: bluenviron/mediamtx
  imageTag: 1.11.3
dlstreamer_pipeline_server:
  image: intel/dlstreamer-pipeline-server
  imageTag: 2026.2.0-ubuntu24-rc1
grafana:
  image: grafana/grafana
  imageTag: 11.5.4
node_red:
  image: nodered/node-red
  imageTag: 4.1
nginx:
  image: nginx
  imageTag: 1.30.2-alpine
metrics_service:
  image: intel/metrics-manager
  imageTag: 2026.2.0-rc1
timezone: ""  # Leave empty; set dynamically at install time: --set timezone=$(cat /etc/timezone)
env:
  ENABLE_WEBRTC: "true"
  ENABLE_RTSP: "true"
  HOST_IP: <HOST_IP>
  ENABLE_HTTPS_MODE: false
  MIN_LOG_LEVEL: DEBUG
  http_proxy:
  https_proxy:
  no_proxy:
  ENABLE_OPEN_TELEMETRY: true
  OTEL_EXPORT_INTERVAL_MILLIS: 5000
gpu:
  enabled: false
  type: "gpu.intel.com/i915"
  count: 1
npu:
  enabled: false
  type: "npu.intel.com/accel"
  count: 1
webrtcturnserver:
  username: <WEBRTC_TURN_SERVER_USERNAME>
  password: <WEBRTC_TURN_SERVER_PASSWORD>
config:
  prometheus:
    name: prometheus
    int:
      prometheus_port: "9090"
  otel_collector:
    name: otel-collector
    int:
      otlp_grpc_port: "4317"
      otlp_http_port: "4318"
      otlp_prometheus_endpoint_port: "9464"
  mediamtx:
    name: mediamtx
    int:
      mediamtx_port: "8889"
      mediamtx_sdp_port: "8189"
      mediamtx_api_port: "9997"
  coturn:
    name: coturn
    int:
      coturn_tcp_port: "3478"
      coturn_udp_port: "3478"
    ext:
      coturn_tcp_port: "30386"
      coturn_udp_port: "30386"
  dlstreamer_pipeline_server:
    name: dlstreamer-pipeline-server
    int:
      rest_api_port: "8080"
      rtsp_output_port: "8554"
  mqtt_broker:
    name: mqtt-broker
    int:
      mqtt_port: "1883"
  grafana:
    name: grafana
    int:
      web_ui_port: "3000"
  node_red:
    name: node-red
    int:
      web_ui_port: "1880"
  nginx:
    name: nginx-reverse-proxy
    int:
      http_port: "80"
      https_port: "443"
    target:
      http_port: "8080"
      https_port: "8443"
    ext:
      http_port: "30080"
      https_port: "30443"
  metrics_service:
    name: metrics-manager
    int:
      metrics_endpoint_port: "9273"
      qmmd_endpoint_port: "9274"
volumes:
  pipelines:
    name: vol-pipelines
    size: 100Mi
    location: "/home/pipeline-server/pipelines"
    hostpath: "/opt/intel/eii/pipelines"
