apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdms-vector-db
  labels:
    {{- include "lvs.vdmsdb.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vdms-vector-db
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/vdms-vector-db-configmap.yaml") . | sha256sum }}
      labels:
        app: vdms-vector-db
        {{- include "lvs.vdmsdb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: vdms-vector-db
          image: {{ .Values.images.vdmsVectorDb }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: vdms-vector-db-config
          ports:
            - containerPort: 55555
              name: vdms
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: vdms-db
              mountPath: /db
      volumes:
        - name: vdms-db
          persistentVolumeClaim:
            claimName: {{ include "lvs.vdmsdb.fullname" . }}-vdms-db
