apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    katenary.v3/compose-hash: 4dd006301f669d044c60fd579bb24fb08133f26f
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "image_based_video_search.labels" . | nindent 4 }}
    katenary.v3/component: dlstreamer-pipeline-server
  name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server'
spec:
  replicas: {{ .Values.dlstreamerpipelineserver.replicas }}
  selector:
    matchLabels:
      {{- include "image_based_video_search.selectorLabels" . | nindent 6 }}
      katenary.v3/component: dlstreamer-pipeline-server
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "image_based_video_search.selectorLabels" . | nindent 8 }}
        katenary.v3/component: dlstreamer-pipeline-server
    spec:
      securityContext:
        supplementalGroups: [109, 110, 992]
      initContainers:
      - name: openvino-container
        image: openvino/ubuntu24_dev:2024.6.0
        env:
          {{- if .Values.httpProxy }}
          - name: http_proxy
            value: "{{ .Values.httpProxy }}"
          - name: HTTP_PROXY
            value: "{{ .Values.httpProxy }}"
          {{- end }}
          {{- if .Values.httpsProxy }}
          - name: https_proxy
            value: "{{ .Values.httpsProxy }}"
          - name: HTTPS_PROXY
            value: "{{ .Values.httpsProxy }}"
          {{- end }}
          {{- if .Values.noProxy }}
          - name: no_proxy
            value: "{{ .Values.noProxy }}"
          - name: NO_PROXY
            value: "{{ .Values.noProxy }}"
          {{- end }}
        command: ["/bin/bash", "-c"]
        args:
          - |
            test -d /output/resnet-50-pytorch || (
              rm -fr /output/resnet-50-pytorch &&
              omz_downloader --name resnet-50-pytorch --output_dir models &&
              omz_converter --name resnet-50-pytorch --download_dir models --output_dir models &&
              cp -r ./models/public/resnet-50-pytorch /output
            ) 
        volumeMounts:
        - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-models'
          mountPath: /output
      - name: model-downloader
        image: intel/dlstreamer:2026.2.0-ubuntu24-rc1
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
        env:
        - name: http_proxy
          value: {{ $.Values.httpProxy }}
        - name: https_proxy
          value: {{ $.Values.httpsProxy }}
        - name: no_proxy
          value: "{{ $.Values.noProxy }}"
        command:
        - /bin/sh
        - -c
        - |
          mkdir -p /output
          cd /tmp/repo/
          git clone --depth 1 --filter=blob:none --sparse \
            {{- if eq $.Values.dlstreamerpipelineserver.modelDownloader.gitSource.type "tag" }}
            --branch {{ $.Values.dlstreamerpipelineserver.modelDownloader.gitSource.ref }} \
            {{- else }}
            --branch {{ $.Values.dlstreamerpipelineserver.modelDownloader.gitSource.ref }} \
            {{- end }}
            https://github.com/open-edge-platform/edge-ai-suites.git

          cd edge-ai-suites
          git sparse-checkout set \
            metro-ai-suite/metro-vision-ai-app-recipe/smart-parking/src/dlstreamer-pipeline-server/models
          cp -r metro-ai-suite/metro-vision-ai-app-recipe/smart-parking/src/dlstreamer-pipeline-server/models/* /output/
          cd /home/dlstreamer/dlstreamer/samples
          rm -rf /tmp/repo/edge-ai-suites
          export MODELS_PATH=/output
          ./download_public_models.sh yolo11s coco128
        volumeMounts:
        - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-models'
          mountPath: /output
        - name: repo-volume
          mountPath: /tmp/repo
      containers:
      - envFrom:
        - configMapRef:
            name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-env'
        env:
        - name: ZE_ENABLE_ALT_DRIVERS
          value: "libze_intel_npu.so"
        image: '{{ tpl .Values.dlstreamerpipelineserver.repository.image $ }}:{{ tpl .Values.dlstreamerpipelineserver.repository.tag $ | default "latest" }}'
        {{- if or (eq .Values.dlstreamerpipelineserver.pipeline "config.gpu.json") (eq .Values.dlstreamerpipelineserver.pipeline "config.npu.json") }}
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: true
          capabilities:
            drop:
              - ALL
        {{- else}}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1999
          capabilities:
            drop:
              - ALL
        {{- end }}
        imagePullPolicy: {{ .Values.dlstreamerpipelineserver.imagePullPolicy }}
        name: dlstreamer-pipeline-server
        command: ["/bin/bash", "-c"]
        args: 
            - |
              ./run.sh
        ports:
        - containerPort: 8080
          name: port-8080
        volumeMounts:
        - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-pipeline'
          mountPath: /home/pipeline-server/config.json
          subPath: {{ .Values.dlstreamerpipelineserver.pipeline }}
        - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-pipeline'
          mountPath: /home/pipeline-server/person-vehicle-bike-detection-2004.json
          subPath: person-vehicle-bike-detection-2004.json
        - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-pipeline-root'
          mountPath: /var/cache/pipeline_root
        - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-models'
          mountPath: /models
        - name: dev-gpu
          mountPath: /dev/dri
          readOnly: true # Reduce risk while preserving access to GPU/NPU devices
        - name: dev-npu
          mountPath: /dev/accel
          readOnly: true # Reduce risk while preserving access to GPU/NPU devices
        {{- if .Values.dlstreamerpipelineserver.resources }}
        resources:
          {{ .Values.dlstreamerpipelineserver.resources | toYaml | nindent 10 }}
        {{- end }}
      volumes:
      - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-pipeline'
        configMap:
          name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-pipeline'
      - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-pipeline-root'
        emptyDir:
          sizeLimit: 1Gi
          medium: Memory
      - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-tmp'
        emptyDir:
          sizeLimit: 1Gi
          medium: Memory
      - name: '{{ include "image_based_video_search.fullname" . }}-dlstreamer-pipeline-server-models'
        emptyDir:
          sizeLimit: 10Gi
      - name: repo-volume
        emptyDir: {}
      - name: dev-gpu
        hostPath:
          path: /dev/dri
      - name: dev-npu
        hostPath:
          path: /dev/accel
      {{- if .Values.pullSecrets }}
      imagePullSecrets:
      {{- .Values.pullSecrets | toYaml | nindent 6 }}
      {{- end }}
      {{- if .Values.dlstreamerpipelineserver.nodeSelector }}
      nodeSelector:
        {{- .Values.dlstreamerpipelineserver.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if ne .Values.dlstreamerpipelineserver.serviceAccount "" }}
      serviceAccountName: {{ .Values.dlstreamerpipelineserver.serviceAccount | quote }}
      {{- end }}
