# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics-manager.fullname" . }}
  labels:
    {{- include "metrics-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "metrics-manager.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
    - name: prometheus
      port: {{ .Values.service.prometheusPort }}
      targetPort: prometheus
