{{/*
Copyright (C) 2026 Intel Corporation
SPDX-License-Identifier: Apache-2.0
*/}}
{{- if and .Values.modelPvc.enabled .Values.global.usePvc (not .Values.modelPvc.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "multimodal-embedding.fullname" . }}-models-pvc
  {{- if .Values.global.keepPvc }}
  annotations:
    helm.sh/resource-policy: keep   # Prevent Helm from deleting PVC on uninstall
  {{- end }}
spec:
  accessModes:
    {{- range .Values.modelPvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.modelPvc.size | default "10Gi" }}
  {{- if .Values.modelPvc.storageClassName }}
    storageClassName: {{ .Values.modelPvc.storageClassName }}
  {{- end }}
{{- end }}
