
name: "[IBVS] Package helm charts weekly "
run-name: "[IBVS] Package helm charts weekly"
on:
  workflow_dispatch:
    inputs:
      helm-chart-tag:
        description: 'Helm chart tag'
        required: true
        type: string
      
permissions: {}
jobs:
  publish-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
    steps:
    - name: Check out edge-ai-suites repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        path: edge-ai-suites-repo
        persist-credentials: false
    - name: Install Helm
      uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 #v4.2.0
      with:
        version: v3.15.2  
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Package Helm Chart
      env:
        HELM_CHART_TAG: ${{ inputs.helm-chart-tag }}
      run: |
        cd edge-ai-suites-repo/metro-ai-suite/image-based-video-search/chart
        helm package . --version "$HELM_CHART_TAG" --app-version "$HELM_CHART_TAG"
    - name: Push to GHCR
      env:
        HELM_CHART_TAG: ${{ inputs.helm-chart-tag }}
      run: |
        CHART_PACKAGE=$(ls edge-ai-suites-repo/metro-ai-suite/image-based-video-search/chart/*-"$HELM_CHART_TAG".tgz)
        helm push $CHART_PACKAGE oci://ghcr.io/${{ github.repository }}/metro-ai-suites/
        
    - name: Update Github Summary
      env:
        HELM_CHART_TAG: ${{ inputs.helm-chart-tag }}
      run: |
        echo "### ✅ Image Based Video Search helm chart published to github container registry" >> $GITHUB_STEP_SUMMARY
          echo "- Registry: \`oci://ghcr.io/${{ github.repository }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Version: \`$HELM_CHART_TAG\`" >> $GITHUB_STEP_SUMMARY
          echo "### Helm Pull Commands" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "helm pull oci://ghcr.io/${{ github.repository }}/metro-ai-suites/image-based-video-search --version $HELM_CHART_TAG" >> $GITHUB_STEP_SUMMARY 
          echo '```' >> $GITHUB_STEP_SUMMARY
    - name: Clean up
      if: always()
      run: |
        rm -rf edge-ai-suites-repo